version: '3.5'

services:
  iwan:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: iwan
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - type: bind
        source: .
        target: /var/www/html
      - type: bind
        source: ./storage/app/public/
        target: /var/www/html/public/storage/
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - iwan

  iwan-mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - iwan-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - iwan-mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    networks:
      backend:
        aliases:
          - phpmyadmin

networks:
  backend:
    name: iwan-network
